services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 6144M
          cpus: "2.0"

volumes:
  redis_data:
